language: node_js
node_js:
- '0.10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
before_script:
script:
- npm install -g bower
- npm install -g gulp
- npm install phantomjs
- npm install -g karma
- bower install --allow-root
- gulp scripts
- gulp inject
- gulp test
- gulp build
branches:
  only:
  - dev
before_deploy:
- gem install heroku
- git remote add heroku git@heroku.com:rented-review.git
- export HEROKU_API_KEY=d606082f-7673-4959-90b4-6cc33a6032e9
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- cd dist
- git init
- git add .
- git -c user.name='travis' -c user.email='travis@travis-ci.org' commit -m "my first commit"
- heroku apps:destroy --app rented-review --confirm rented-review
- heroku create rented-review
- git remote -v
- heroku git:remote -a rented-review
deploy:
  provider: heroku
  app: rented-review
  api_key:
    secure: igoyaN1Qw+IgZkLuseRA9Ss0abg5qVjaONzdVK5mOHJPoHpAWm2wmXYnfazN4yq3edKjEbXa21wy49sZA9XFvrWGA8K8h934XIeDnVbNI304jTDb5HLv8Ii5KYJ5s1XbXFmZkOZxWQMQlC/yTr6rF72UXFUUXYfQDjBL2C4EUxVF81JWmyWI/HmhETrQJ5jxDzSTYjhd/ygzXeoiBF3UD1STXSSnrnNaJtxwXM4NIyNAFp2BNEhxZuIN3FK/oYYUxRGD52yIPam1I6WxFGdICZcdxhO4/0YVE6L8+5TpWCQmk7cBWK2pmpUJDIyl7aGHmHb8dHw1WbsPx8wmTZqCWM2MtK15Zdpadjq4jdHx/KpANGv5472YlEqcdBoLjJj46ATiCJ1t7VPBJYbFm5ViYCgy5G05f0IMeXwlK2B2XTAcFEr+g5b+k23sVaMsrzMqjmU0iN4WMaoVey00x8xthD36QcSHp+CskHWwAOgKuus4n5XnKtldTZvMsvfLdFT4Z8yM8jjZgoRyHJhRiyRvLQ13UgWfkfJi1q33XrE1Bvnx4o56jB2zi72Uiey5T/o+8kgWZqSmB7QXEk845ikeMIA4iU4/LfuTrA/IeuIGWGBcODrvMDyus+LnObehqC2+fDPl54QenT8XKez/QAAptxzfBz6B5kdft8qxFRt7L5A=
  on: dev
